### ISSUE TITLE
Bypass env variables into a docker container

### ISSUE THREAD

**Issue by Khatskevich** [packpack/packpack#100]
I have faces 2 situations where I had to pass some product-specific variables from Travis env into a docker image.

I suggest introducing special variables: `PACKPASS_XYZ="VAR"` which are exported into the docker as
`XYZ="VAR"`.

**Comment by knight-of-ni** [comment]
I second this. 
This should allow me to easily set `PACKPASS_DEBUILD_LINTIAN="no"` to skip lintian checking, rather than patch in the `--no-lintian` flag each time I run packpack, which is what I am doing now.

Skipping lintian checks not only speeds up the build significantly, but it also avoids a boatload of output, which counts against the infamous Travis CI log output limit.

**Comment by Totktonada** [comment]
@Khatskevich Can you please provide a link to the project (preferably to the patch) where you are hit this need?

**Comment by Totktonada** [comment]
I would better list variables, which should be preserved from a parent environment. This way we don't need to set `FOO`'s value to `PACKPASS_FOO` in order to access `FOO` from a tool that is executed under rpmbuild / debuild, which is run under packpack.

We have CI jobs, which runs the same [tool](https://github.com/tarantool/test-run/) in different ways: directly or under packpack. I want to setup variables once and use them everywhere.
