### ISSUE TITLE
Package version is always 0.0.1

### ISSUE THREAD

**Issue by ubunteroz** [packpack/packpack#2]
Git shows correct annotated tag and revision:
`$ git describe --always --long`
`v1.1.7-1-g4499329`

But, Packpack keeps using version 0.0.1 which causing build error on my project. Please take a look: https://travis-ci.org/ubunteroz/ignsdk-debian/jobs/173788190

Btw, thanks for your great project, it's really cool!

**Comment by ubunteroz** [comment]
Fixed, it seems that Packpack doesn't recognize alphabet in versioning scheme. I changed to 1.1.7 and it worked.

**Comment by rtsisyk** [comment]
PackPack uses the `major.minor` versioning scheme, see config.mk:
https://github.com/packpack/packpack/blob/00ee077c2218a42586624d24411b574ae5d6ff55/pack/config.mk#L39

You can override this logic via VERSION environment variable:

    VERSION=$(git describe --long --always | sed -n 's/^v\([0-9\.]*\)-\([0-9]*\)-\([a-z0-9]*\)/\1.\2/p') packpack

I plan to add more ways to override configuration options in the near future.

>  I changed to 1.1.7 and it worked.

I suggest to use 1.1 instead. PackPack automatically extract the number of commits since the tag and appends its to the version, e.g. 1.1.7-223-gXXX  will produce 1.1.7.223.

> Btw, thanks for your great project, it's really cool!

Thanks a lot. Your bug reports and pull requests are welcome ;)
