### ISSUE TITLE
Build failure due to source tarball filename mismatch

### ISSUE THREAD

**Issue by knnniggett** [packpack/packpack#58]
I am much more familiar with building rpm's than deb's so the following could easily be something on my end rather than packpack. I was hoping someone could help me troubleshoot this.

I cannot get any debian based packpack build to report success because packpack is looking for the source tarball `/build/zoneminder_1.30.2.0-1.debian.tar.xz` which does not exist. Instead the file which does exist is called `/build/zoneminder_1.30.2.0-1.tar.xz`.

It seems the word "debain" in the filename is hardcoded:
https://github.com/packpack/packpack/blob/master/pack/deb.mk#L17

Steps to reproduce:
```
$ git tag -a 1.30.2
$ OS=ubuntu DIST=xenial packpack/packpack
```

At the start of the build, I see:
`dpkg-source: info: building zoneminder in zoneminder_1.30.2.0-1.tar.xz`

However, during the final step of the build I get:
`ls: cannot access '/build/zoneminder_1.30.2.0-1.debian.tar.xz': No such file or directory`

Deb packages are indeed created, but the build still returns failure due to the "missing" tarball.

Full build output can be viewed here:
https://gist.githubusercontent.com/knnniggett/9036f11fb5945fa88be4fcfe0eef3616/raw/cb54216b53f6f12e2155194bf6f448a3cba8df3d/gistfile1.txt

Our debain build scripts are here (gets linked to /debian just prior to calling packpack):
https://github.com/ZoneMinder/ZoneMinder/tree/master/distros/ubuntu1604

**Comment by rtsisyk** [comment]
Hi, thanks for the your interest in this project.

Debian has two type of tarballs:

* name-version.orig.tar.gz - original upstream sources, usually without `debian/` directory
* name-version-release.debian.tar.gz - "debian/" directory

PackPack  automatically creates .orig.tar.gz from git whereas `name-version-release.debian.tar.gz ` is created by `dpkg`.

Could you please send me a link to your repository/branch? I'll try to fix PackPack for your case.
P.S.: I'm former ZoneMinder user :)

**Comment by knnniggett** [comment]
You bet. Just clone the master branch:
https://github.com/ZoneMinder/ZoneMinder

Before running packpack, you will need to symlink the appropriate distro folder. For ubuntu 1604 that would be: `ln -s distros/ubuntu1604 debian`

When I run packpack, zoneminder_x.x.xx.tar.xz is saved in the build folder. A symlink called zoneminder_x.x.xx.orig.tar.xz points to zoneminder_x.x.xx.tar.x, but of course zoneminder_x.x.xx.debian.tar.xz is not there.

Thanks for the help.

**Comment by rtsisyk** [comment]
I experimented with ZoneMinder's Debian package and found that PackPack doesn't handle "3.0 (native)" source format properly. Currently only "quilt" packages are fully supported. I'm working on the fix. ETA is Sunday.

**Comment by rtsisyk** [comment]
It was easier than I expected. Current solution is to automatically convert `3.0 (native)` sources to `3.0 (quilt)`. Please try the latest version of PackPack to build ZoneMinder:

```
$ git describe
1.30.2-9-gf9c6742
$ export VERSION=$(git describe --long --always | sed -n 's/^\([0-9\.]*\)-\([0-9]*\)-\([a-z0-9]*\)/\1/p')
$ export RELEASE=$(git describe --long --always | sed -n 's/^\([0-9\.]*\)-\([0-9]*\)-\([a-z0-9]*\)/\2/p')
$ echo VERSION=$VERSION RELEASE=$RELEASE
VERSION=1.30.2 RELEASE=9
$ OS=ubuntu DIST=xenial packpack
```

Please note that in the code snippet above I overrode VERSION and RELEASE variables to match versioning scheme used by ZoneMinder. By default PackPack converts `major.minor-commitcount-githash` output of `git describe` to `VERSION=major.minor.commitcount RELEASE=1`, which works perfectly when you use "major.minor" (without "patch" level) for annotated tags (see [SemVer](http://semver.org/) for definitions).

According to Debian policies and Fedora Guidelines, VERSION should be the actual version of software, whereas RELEASE is the number of times this package has been repackaged by a package maintaner or rebuilt by automated tools. In our case, `1.30.2-9-gf9c6742` means that ZoneMinder itself has been changed 9 times since `1.30.2` tag, so "9" probably should be included somewhere in VERSION.
Anyway, I found that VERSION=1.30.2 RELEASE=9 is also convenient and acceptable if you don't plan to upload these packages to the upstream distributions.

**Comment by knnniggett** [comment]
This is working now. Thank you.
