### ISSUE TITLE
New feature request: Keep a CHANGELOG

### ISSUE THREAD

**Issue by sergeyklay** [packpack/packpack#65]
I propose to introduce "semantic changelog":  https://keepachangelog.com/en/1.0.0/

**Comment by rtsisyk** [comment]
I think that [GitHub Releases][Releases] is the best place for changelogs. I didn't care about the release management for this project until now. Thanks for the help of our active commiters, PackPack has grown from a proof-of-concept `travis.sh` script to a standalone tool used by multiple projects in the pace I couldn't expect.

Now it is time to improve this situation. The common way to create CHANGELOG entries is to assign a [milestone][Issues] to every GitHub ticket and then aggregate this information into the [releases notes](Releases) when a new release is tagged in git. See [an example](https://github.com/tarantool/tarantool/releases) from another project I contribute to. I already added milestones and labels to all old tickets. Now you can see the full changelog since initial release (1.0) by setting ["milestone:1.1"][Issues] filter in Github Issues. 

I see that 1.1 milestone has already got enough changes an it's time to release it and move to 1.2. I will manage to make a release and update [Github Releases][Releases] in the next couple weeks.

[Issues]: https://github.com/packpack/packpack/issues?utf8=%E2%9C%93&q=milestone%3A1.1%20is%3Aclosed%20
[Releases]:  https://github.com/packpack/packpack/releases
