### ISSUE TITLE
Centos7 Build Error

### ISSUE THREAD

**Issue by RepentantGopher** [packpack/packpack#96]
Got this error while attempt 
```bash
make -f ./packpack/pack/Makefile BUILDDIR=$(pwd) OS=el DIST=7
```

```bash
Installing dependencies
-------------------------------------------------------------------
if [ -n "" ] && [ -n "" ]; then \
	curl -s https://packagecloud.io/install/repositories///script.rpm.sh | sudo bash; \
fi
sudo dnf builddep -y /builds/tarantool/mf-sls/vshard-zookeeper/tarantool-vshard-zookeeper-0.0.1-1.el7.centos.src.rpm || sudo yum-builddep -y /builds/tarantool/mf-sls/vshard-zookeeper/tarantool-vshard-zookeeper-0.0.1-1.el7.centos.src.rpm
sudo: dnf: command not found
Loaded plugins: fastestmirror, ovl
Enabling base-source repository
Enabling centos-sclo-sclo-source repository
Enabling epel-source repository
Enabling extras-source repository
Enabling updates-source repository
Loading mirror speeds from cached hostfile
 * base: mirrors.greenmountainaccess.net
 * epel: mirror.us.leaseweb.net
 * epel-source: mirror.us.leaseweb.net
 * extras: mirrors.advancedhosters.com
 * updates: mirror.siena.edu
Checking for new repos for mirrors
Error: Could not open /builds/tarantool/mf-sls/vshard-zookeeper/tarantool-vshard-zookeeper-0.0.1-1.el7.centos.src.rpm .
Try running yum-builddep with the --nogpgcheck option.
There was a problem getting the build deps, exiting:
   Could not open local rpm file: /builds/tarantool/mf-sls/vshard-zookeeper/tarantool-vshard-zookeeper-0.0.1-1.el7.centos.src.rpm: Unable to open file
/builds/tarantool/mf-sls/vshard-zookeeper/packpack/pack//rpm.mk:122: recipe for target 'package' failed
make: *** [package] Error 1
rm /builds/tarantool/mf-sls/vshard-zookeeper/VERSION /builds/tarantool/mf-sls/vshard-zookeeper/ls-lR.txt
ERROR: Job failed: exit code 1
```

It seems this is related to https://github.com/packpack/packpack/issues/68

**Comment by Totktonada** [comment]
> Error: Could not open /builds/tarantool/mf-sls/vshard-zookeeper/tarantool-vshard-zookeeper-0.0.1-1.el7.centos.src.rpm .
> ...
> Could not open local rpm file: /builds/tarantool/mf-sls/vshard-zookeeper/tarantool-vshard-zookeeper-0.0.1-1.el7.centos.src.rpm: Unable to open file

This is output of [this][1] command. It seems source RPM package was not created or was deleted after building source RPM. In the former case an actual error is somewhere above pasted output (but don't sure why it does not set exit code >0 in the case). The reason of the later case can be some cleanup rpmbuild does (don't sure), maybe because `$(PWD)` is used as the build directory.

Check output carefully to verify whether the reason is the first one. Use separate build directory to verify whether the reason is the second one.

[1]: https://github.com/packpack/packpack/blob/2b9788eef46c2fcb9dd5761d431bf555182a6335/pack/rpm.mk#L136

**Comment by Totktonada** [comment]
Feel free to reopen with more information.
